#!/usr/bin/env python3
"""Derive the three small tables the ZWNJ and ZWJ exemptions need, as a C++
header compiled into the library.

The port reads its UCD tables from a directory at runtime, and its public
data-free `scan` therefore holds none. Without data neither exemption is
decidable, so that entry point reported every ZERO WIDTH NON-JOINER and
rejected ordinary Devanagari and Persian text, which the Lean reference proves
clear. The three inputs the two rules actually consult are small enough to
compile in, so the exemptions hold on every path and the data-free mode stops
being a reduced reading.

Only derived facts are emitted, never a copy of a UCD file: the Virama set is
the codepoints with Canonical_Combining_Class 9, the joining rows are the
Joining_Type ranges, and the alphabet is the codepoints occurring in a
registered RGI emoji ZWJ sequence.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
OUT = ROOT / "include" / "unicode_cpp" / "security" / "generated" / "context_tables.hpp"

ZWJ = 0x200D


def strip_comment(line):
    return line.split("#", 1)[0].strip()


def parse_range_token(token):
    token = token.strip()
    if ".." in token:
        lo, hi = token.split("..", 1)
        return int(lo, 16), int(hi, 16)
    cp = int(token, 16)
    return cp, cp


def virama_codepoints():
    """Codepoints with Canonical_Combining_Class 9. A ZWNJ directly after one
    suppresses a conjunct, which is how a Devanagari cluster is written."""
    out = []
    for line in (DATA / "UnicodeData.txt").read_text(encoding="utf-8").splitlines():
        fields = line.split(";")
        if len(fields) > 3 and fields[3] == "9":
            out.append(int(fields[0], 16))
    return sorted(out)


def joining_rows():
    """Joining_Type ranges, as (lo, hi, token). The file's @missing line
    declares Non_Joining over the whole space, so an unlisted codepoint needs
    no row."""
    rows = []
    for line in (DATA / "DerivedJoiningType.txt").read_text(encoding="utf-8").splitlines():
        body = strip_comment(line)
        if not body or ";" not in body:
            continue
        left, token = [part.strip() for part in body.split(";")[:2]]
        if token not in ("C", "D", "L", "R", "T"):
            continue
        lo, hi = parse_range_token(left)
        rows.append((lo, hi, token))
    rows.sort()
    return rows


def rgi_alphabet():
    """Every codepoint occurring at any position of a registered RGI emoji ZWJ
    sequence, excluding the joiner. A ZWJ is sanctioned only when flanked by
    two of these."""
    alphabet = set()
    for line in (DATA / "emoji-zwj-sequences.txt").read_text(encoding="utf-8").splitlines():
        body = strip_comment(line)
        if not body or ";" not in body:
            continue
        for token in body.split(";")[0].split():
            try:
                cp = int(token, 16)
            except ValueError:
                continue
            if cp != ZWJ:
                alphabet.add(cp)
    return sorted(alphabet)


TOKEN_TO_ENUM = {
    "C": "JoiningType::JoinCausing",
    "D": "JoiningType::DualJoining",
    "L": "JoiningType::LeftJoining",
    "R": "JoiningType::RightJoining",
    "T": "JoiningType::Transparent",
}


def main():
    viramas = virama_codepoints()
    rows = joining_rows()
    alphabet = rgi_alphabet()

    lines = [
        "// GENERATED by tools/generate_context_tables.py - do not edit by hand.",
        "//",
        "// The three derived tables the RFC 5892 Appendix A.1 ZWNJ rule and the",
        "// registered-emoji ZWJ rule consult, compiled in so both hold even when the",
        "// caller supplies no UCD directory. Regenerate after any UCD version bump.",
        "",
        "#ifndef UNICODE_CPP_SECURITY_GENERATED_CONTEXT_TABLES_HPP",
        "#define UNICODE_CPP_SECURITY_GENERATED_CONTEXT_TABLES_HPP",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "#include \"unicode_cpp/security/identity/ucd.hpp\"",
        "",
        "namespace unicode_cpp::security::generated {",
        "",
        "using unicode_cpp::security::ucd::JoiningType;",
        "",
        "struct JoiningRow {",
        "    std::uint32_t lo;",
        "    std::uint32_t hi;",
        "    JoiningType cls;",
        "};",
        "",
        f"inline constexpr std::array<std::uint32_t, {len(viramas)}> kViramaCodepoints{{{{",
    ]
    lines.extend(f"    0x{cp:04X}," for cp in viramas)
    lines.append("}};")
    lines.append("")
    lines.append(f"inline constexpr std::array<JoiningRow, {len(rows)}> kJoiningRows{{{{")
    for lo, hi, token in rows:
        lines.append(f"    {{0x{lo:04X}, 0x{hi:04X}, {TOKEN_TO_ENUM[token]}}},")
    lines.append("}};")
    lines.append("")
    lines.append(f"inline constexpr std::array<std::uint32_t, {len(alphabet)}> kRgiZwjAlphabet{{{{")
    lines.extend(f"    0x{cp:04X}," for cp in alphabet)
    lines.append("}};")
    lines.extend([
        "",
        "}  // namespace unicode_cpp::security::generated",
        "",
        "#endif  // UNICODE_CPP_SECURITY_GENERATED_CONTEXT_TABLES_HPP",
        "",
    ])

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="ascii")
    print(
        f"generated {OUT.relative_to(ROOT)}: "
        f"{len(viramas)} viramas, {len(rows)} joining rows, "
        f"{len(alphabet)} alphabet entries"
    )


if __name__ == "__main__":
    main()
