"""Security Conformance Layer — detector families and shared vocabulary.

The package's public surface re-exports the per-family detectors
along with the shared verdict vocabulary (``Family``, ``Severity``,
``AdversaryTier``, ``ClassificationKind``, ``HazardPosition``,
``KeyValueAttribution``).
"""

from . import covert, identity, policy
from .calculus import (
    AdversaryTier,
    ClassificationKind,
    Family,
    HazardPosition,
    KeyValueAttribution,
    Severity,
    default_severity,
)
from .policy import (
    Action,
    CryptoContext,
    Finding,
    Mode,
    PolicyLevel,
    Profile,
    ProfilePolicy,
    Verdict,
    blocking_findings,
    family_blocks,
    family_layer_code,
    family_slug,
    finding_to_wire,
    permits,
    policy_of_profile,
    reason_base,
    reason_code,
    rejection_set,
    scan,
    scan_default,
    scan_utf16be,
    scan_utf16le,
    scan_utf32be,
    scan_utf32le,
    scan_utf8,
    select_action,
    utf8_reject_tag,
    verdict_to_json,
    verdict_to_wire,
)

__all__ = [
    "Action",
    "AdversaryTier",
    "ClassificationKind",
    "CryptoContext",
    "Family",
    "Finding",
    "HazardPosition",
    "KeyValueAttribution",
    "Mode",
    "PolicyLevel",
    "Profile",
    "ProfilePolicy",
    "Severity",
    "Verdict",
    "blocking_findings",
    "covert",
    "default_severity",
    "family_blocks",
    "family_layer_code",
    "family_slug",
    "finding_to_wire",
    "identity",
    "permits",
    "policy",
    "policy_of_profile",
    "reason_base",
    "reason_code",
    "rejection_set",
    "scan",
    "scan_default",
    "scan_utf16be",
    "scan_utf16le",
    "scan_utf32be",
    "scan_utf32le",
    "scan_utf8",
    "select_action",
    "utf8_reject_tag",
    "verdict_to_json",
    "verdict_to_wire",
]
